### ISSUE TITLE
编译PSU时遇到的问题

### ISSUE THREAD

**Issue by Yukinaaaaa** [dujiajun/PSU#1]
配置完成libOTe后，在编译PSU时出现了问题。
![image](https://user-images.githubusercontent.com/74668748/170233780-52631038-dd56-4110-82b8-505c688f5cd0.png)
![image](https://user-images.githubusercontent.com/74668748/170234047-7d929ee9-1a99-491a-bccf-fe1a8bba6b1f.png)
这里显示引用路径不正确，在libOTe中，我更正了路径。
![image](https://user-images.githubusercontent.com/74668748/170234169-588007ef-8df0-4da8-b0b0-49e8693eaf87.png)
![image](https://user-images.githubusercontent.com/74668748/170234191-85d550a7-cb29-4f53-adf2-07867b1a283f.png)
Defines.h文件中引用了config.h，但是我发现config.h并不在在libOTe的cryptoTools/Common中。
请问这是出现了什么问题。

**Comment by dujiajun** [comment]
config.h 是 libOTe 编译的时候通过 config.h.in 自动生成的，你可能要先看下 libOTe 是否正确编译。

**Comment by Yukinaaaaa** [comment]
谢谢你
libOTe正确编译并且链接上了
![image](https://user-images.githubusercontent.com/74668748/170254615-e9ab41b0-d001-4d64-bc51-e0a674f3849e.png)

no type named ‘const_iterator’ in ‘class std::span<std::array<osuCrypto::block, 2>, 18446744073709551615>’
请问这个应该怎么解决？
![image](https://user-images.githubusercontent.com/74668748/170254547-dcca0766-44b6-461a-8ba9-54fd3f666eb8.png)

使用cryptoTools？

**Comment by dujiajun** [comment]
我不太清楚，看上去是libOTe或者cryptoTools的问题，不是我这一层的问题。

**Comment by Yukinaaaaa** [comment]
好的谢谢你
